# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build for x86_64 Linux
      run: |
        mkdir artifacts/
        GOARCH=amd64 GOOS=linux go build -v -o artifacts/auto-cf-protector-amd64 ./...

    - name: Build for ARM64 Linux
      run: |
        GOARCH=arm64 GOOS=linux go build -v -o artifacts/auto-cf-protector-arm64 ./...

    - name: Setting execution permissions
      run: |
        chmod +x artifacts/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-artifacts
        path: artifacts/
